2021-11-08 02:05:40 DEBUG Log file at: /home/zhujunhua/workspace/cangjie/utils/test-framework/test_temp/log/HLT/API/Filesystem/os_chown_0.cj_cangjie2llvmgc_test_cfg.log
2021-11-08 02:05:40 DEBUG Work directory: /home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/API/Filesystem/os_chown_0_cj_cangjie2llvmgc_test_cfg_1636335531
2021-11-08 02:05:40 DEBUG execute cmd ===>>>: cjc -backend llvm caserunner.cj -o os_chown_0.out os_chown_0.cj
2021-11-08 02:05:42 DEBUG return code: 0
2021-11-08 02:05:42 DEBUG stdout : 

2021-11-08 02:05:42 DEBUG stderr : 
@	/home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/API/Filesystem/os_chown_0_cj_cangjie2llvmgc_test_cfg_1636335531/caserunner.cj:33:5: [33mwarning[0m: unhandled items after throw expr
@	   33 |     }
@	      |     [32m^[0m
@	/home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/API/Filesystem/os_chown_0_cj_cangjie2llvmgc_test_cfg_1636335531/caserunner.cj:186:19: [33mwarning[0m: 'x' has been defined in the outside of match expression, are you sure using 'x' as a variable pattern here?
@	  186 |         case Some(x) => x
@	      |                   [32m^[0m
@	2 warnings generated

2021-11-08 02:05:42 DEBUG Run time: 2.3, remain time: 3e+02
2021-11-08 02:05:42 DEBUG execute cmd ===>>>:   os_chown_0.out 
2021-11-08 02:05:42 DEBUG return code: 0
2021-11-08 02:05:42 DEBUG stdout : 
+	==============Test Case chown()入参 Start==============
+	AssertionError: test failed at 0 
+	-------------Test Result------------------------------
+	PASS: 0
+	FAIL: 1
+	TOTAL: 1
+	==============Test End=================================
+	

2021-11-08 02:05:42 DEBUG stderr : 

2021-11-08 02:05:42 DEBUG Run time: 0.039, remain time: 3e+02
2021-11-08 02:05:42 DEBUG execute cmd ===>>>:   os_chown_0.out 
2021-11-08 02:05:42 DEBUG return code: 0
2021-11-08 02:05:42 DEBUG stdout : 
+	==============Test Case chown()入参 Start==============
+	AssertionError: test failed at 0 
+	-------------Test Result------------------------------
+	PASS: 0
+	FAIL: 1
+	TOTAL: 1
+	==============Test End=================================
+	

2021-11-08 02:05:42 DEBUG stderr : 

2021-11-08 02:05:42 DEBUG Run time: 0.047, remain time: 3e+02
2021-11-08 02:05:42 DEBUG execute cmd ===>>>: pwd
2021-11-08 02:05:42 DEBUG return code: 0
2021-11-08 02:05:42 DEBUG stdout : 
+	/home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/API/Filesystem/os_chown_0_cj_cangjie2llvmgc_test_cfg_1636335531

2021-11-08 02:05:42 DEBUG stderr : 

2021-11-08 02:05:42 DEBUG Run time: 0.017, remain time: 3e+02
2021-11-08 02:05:42 DEBUG execute cmd ===>>>: ls -l test_fj.txt|  /usr/bin/python3 /home/zhujunhua/workspace/cangjie/utils/test-framework/maple_test/compare.py --comment=// os_chown_0.cj
2021-11-08 02:05:42 DEBUG return code: 1
2021-11-08 02:05:42 DEBUG stdout : 
+	compare.py input:
+		-rw-rw-r-- 1 zhujunhua zhujunhua 0 Nov  8 01:38 test_fj.txt
+	
+	compare.py input end
+	
+	Starting Compare:
+	b"It's a assert, flag: scan, pattern:  fj docker , result: False, matched at output line: 0"
+	Match End!, Compare Failed
+	b"It's a assert, flag: scan, pattern:  test_fj.txt , result: True, matched at output line: 0"
+	b"It's a assert, flag: regex-auto, pattern: -rw-rw-r-- , result: True, matched at output line: 2"

2021-11-08 02:05:42 DEBUG stderr : 

2021-11-08 02:05:42 DEBUG Run time: 0.11, remain time: 3e+02
2021-11-08 02:05:42 ERROR Failed, return code 1 should be 0!
 Log file at: /home/zhujunhua/workspace/cangjie/utils/test-framework/test_temp/log/HLT/API/Filesystem/os_chown_0.cj_cangjie2llvmgc_test_cfg.log
